<?php
/**
 * This file is part of Kokx's CR Converter.
 *
 * Kokx's CR Converter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Kokx's CR Converter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Kokx's CR Converter.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   KokxConverter
 * @license    http://www.gnu.org/licenses/gpl.txt
 * @copyright  Copyright (c) 2009 Kokx
 * @package    Kokx_Render
 */
?>
<html>
	<head>
		<title><?= $this->translate("Kokx's OGame CR converter") ?></title>
		<script type="text/javascript" src="/js/main.js"></script>
		<link rel="stylesheet" type="text/css" media="screen, handheld, projection" href="css/main.css" />
	</head>

	<body>
		<div id="main-container">
			<div id="lang">
				<div id="lang-nl" class="lang<?= ($this->translate()->getTranslator()->getLocale() == 'nl') ? ' lang-selected' : ''; ?>">
					<a href="?lang=nl">
						<div><img src="./images/flags/Netherlands-Flag.png" alt="Netherlands" /></div>
						<div>Nederlands</div>
					</a>
				</div>
				<div id="lang-en" class="lang<?= ($this->translate()->getTranslator()->getLocale() == 'en') ? ' lang-selected' : ''; ?>">
					<a href="?lang=en">
						<div><img src="./images/flags/United-Kingdom-flag.png" /></div>
						<div>English</div>
					</a>
				</div>
				<div id="adsense">
					<?= $this->render('partial/adsense.phtml'); ?>
				</div>
				<div class="clear"></div>
			</div>
			<div id="header">
				<h1><?= $this->translate("Kokx's OGame CR converter") ?> </h1>
				<div id="agslord"><a href="ags_winstverdeler_2013.xlsx">AGS Winstverdeler van Lord</a></div>
				<div class="clear"></div>
			</div>
			
			<div id="container">
				<?= $this->layout()->content; ?>
			</div>

			<div id="footer">
				Kokx's CR Converter  Copyright (C) 2013 kokx & Vii & Warsaalk <br/>
				This program comes with ABSOLUTELY NO WARRANTY; for details, <a href="COPYING.html#section15">click here</a>. <br/>
				This is free software, and you are welcome to redistribute it <br/>
				under certain conditions; <a href="COPYING.html#terms">click here</a> for details. <br/>
			</div>
		</div>

		<? /* Google Analytics code */ ?>
		<script type="text/javascript">
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-17752066-3']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
    </body>
</html>
